---
- name: Play for installing the Nginx
  hosts: all
  #remote_user: root
  tasks: 
  - name: performing apt update
    shell:  apt update 
# before running the script ake sure to clone the reository "https://github.com/gopichandnallani/webpage-test.git"
# all the files that we are copying are in that repository.
# clone in the local system where you are running the Ansible not on client machines.
  - name: installing nginx
    apt: >
      name=nginx
      state=present
  - name: copying files to the server 
    copy: 
      src:  webpage-test/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: copying the files to server style.css
    copy:
      src: webpage-test/style.css
      dest: /var/www/html/style.css
      owner: root
      group: root
      mode: 0644

  - name: 
    copy:
      src: webpage-test/scorekeeper.js
      dest: /var/www/html/scorekeepeer.js
      owner: root
      group: root
      mode: 0644

  - name: Start nginx service 
    shell: service nginx start
