---
- name: play for installing nginx on webservers
  hosts: all
  #remote_user: root
  vars:
    custom_heading: "Welcome to the BG it solutins"
    todays_date: "{{ ansible_facts['date_time']['date'] }}"
    host_name: "{{ ansible_facts['hostname']}}"
  
  tasks:
    - name: run apt update 
      shell: apt update -y 
    - name: install nginx server
      apt: >
        name=nginx
        state=present
    - name: 
