---
- name: create set of users
  hosts: all
  gather_facts: yes
  tasks: 
    - name: creating users 1,2,3,4,5,6
      user: >
        name={{ item }}
        shell=/bin/bash
        password='adehycbukebhyukb237827398y293r2bfcek'
      with_items:
        - testuser1
        - testuser2
        - testuser3
        - testuser4
        - testuser5
      when:
        ansible_os_family == "Debian"
